swagger: '2.0'
info:
  description: 'http://swagger.io'
  version: 1.0.0
  title: Swagger Acme Producer
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: acme.swagger.io
basePath: /v2
tags:
  - name: caixa
    description: Tudo sobre faturas
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: servico
    description: Tudo sobre intalacao
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: usuario
    description: Tudo sobre clientes
    externalDocs:
      description: Find out more 
      url: 'http://swagger.io'
schemes:
  - https
  - http
paths:
  /caixa:
    post:
      tags:
        - caixa
      summary: Adicionar nova fatura
      description: ''
      operationId: addFatura
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Fatura a ser adicionada
          required: true
          schema:
            $ref: '#/definitions/Fatura'
      responses:
        '405':
          description: Invalid input
      security:
        - acme_auth:
            - 'write:acme'
            - 'read:acme'
    get:
      tags:
        - caixa
      summary: Gel all Fatura
      operationId: getAllFatura
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Fatura'
        '400':
          description: Invalid ID supplied
        '404':
          description: Fatura not found
      security:
        - api_key: []
  '/caixa/{codigo}':
    get:
      tags:
        - caixa
      summary: Fatura por codigo
      description: Returns a single pet
      operationId: getFaturaByCodigo
      produces:
        - application/xml
        - application/json
      parameters:
        - in: path
          name: codigo
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Fatura'
        '400':
          description: Invalid ID supplied
        '404':
          description: Fatura not found
    delete:
      tags:
        - caixa
      summary: Exclui fatura por codigo
      description: ''
      operationId: deleteFaturaCodigo
      produces:
        - application/xml
        - application/json
      parameters:
        - name: codigo
          in: path
          required: true
          type: string
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Fatura not found
  /servico/instalacao:
    post:
      tags:
        - servico
      summary: Criar Instalacao
      description: ''
      operationId: placeInstalacao
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Criar Instalacao
          required: true
          schema:
            $ref: '#/definitions/Instalacao'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Instalacao'
        '400':
          description: Invalid Instalacao
    get:
      tags:
        - servico
      summary: Get all Instalacao
      description: ''
      operationId: getAllInstalacao
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Instalacao'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
  '/servico/instalacao/{codigo}':
    get:
      tags:
        - servico
      summary: Get instalacao por codigo
      description: ''
      operationId: getInstalacaoByCodigo
      produces:
        - application/xml
        - application/json
      parameters:
        - name: codigo
          in: path
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Instalacao'
        '400':
          description: Invalid codigo supplied
        '404':
          description: Instalacao not found
    delete:
      tags:
        - servico
      summary: Delete Instalacao por codigo
      description: ''
      operationId: deleteInstalacao
      produces:
        - application/xml
        - application/json
      parameters:
        - name: codigo
          in: path
          required: true
          type: string
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Instalacao not found
  '/servico/instalacao/cliente/{cpf}':
    get:
      tags:
        - servico
      summary: Get instalacao por cpf
      description: ''
      operationId: getInstalacaoByCpf
      produces:
        - application/xml
        - application/json
      parameters:
        - name: cpf
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Instalacao'
        '400':
          description: Invalid codigo supplied
        '404':
          description: Instalacao not found
    delete:
      tags:
        - servico
      summary: Delete Instalacao por cpf
      description: ''
      operationId: deleteInstalacaoCpf
      produces:
        - application/xml
        - application/json
      parameters:
        - name: cpf
          in: path
          required: true
          type: integer
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Instalacao not found
  /usuario:
    post:
      tags:
        - usuario
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createusuario
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        default:
          description: successful operation
    get:
      tags:
        - usuario
      summary: Get all users
      description: ''
      operationId: getAllUsers
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Cliente'
        '400':
          description: Invalid nome supplied
        '404':
          description: usuario not found
  '/usuario/{cpf}':
    get:
      tags:
        - usuario
      summary: Get user by user cpf
      description: ''
      operationId: getusuarioByCpf
      produces:
        - application/xml
        - application/json
      parameters:
        - name: cpf
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Cliente'
        '400':
          description: Invalid nome supplied
        '404':
          description: usuario not found
    put:
      tags:
        - usuario
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateusuario
      produces:
        - application/xml
        - application/json
      parameters:
        - name: cpf
          in: path
          description: name that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        '400':
          description: Invalid user supplied
        '404':
          description: usuario not found
    delete:
      tags:
        - usuario
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteusuario
      produces:
        - application/xml
        - application/json
      parameters:
        - name: cpf
          in: path
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        '400':
          description: Invalid nome supplied
        '404':
          description: usuario not found
securityDefinitions:
  acme_auth:
    type: oauth2
    authorizationUrl: 'http://acme.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:acme': modificar dados
      'read:acme': ler dados
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Fatura:
    type: object
    properties:
      id:
        type: integer
        format: int64
      codigo:
        type: string
      numero_leitura:
        type: string
      data_vencimento:
        type: string
        format: date-time
      data_leitura:
        type: string
        format: date-time
      valor_conta:
        type: number
      instalacao:
        $ref: '#/definitions/Instalacao'
    xml:
      name: Fatura
  Endereco:
    type: object
    properties:
      id:
        type: integer
        format: int64
      bairro:
        type: string
      cidade:
        type: string
      logradouro:
        type: string
      numero:
        type: integer
      uf:
        type: string
    xml:
      name: Endereco
  Cliente:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nome:
        type: string
      cpf:
        type: string
      data_nascimento:
        type: string
        format: date-time
      endereco:
        $ref: '#/definitions/Endereco'
    xml:
      name: Cliente
  Instalacao:
    type: object
    properties:
      id:
        type: integer
        format: int64
      codigo:
        type: string
      data_instalacao:
        type: string
        format: date-time
      cliente:
        $ref: '#/definitions/Cliente'
      endereco:
        $ref: '#/definitions/Endereco'
    xml:
      name: Instalacao
